сделана вторая домашка
trichinella/learn-javascript-react pull request #2
Opened 2024-07-13 12:55 UTC by trichinella

2024-07-13 14:18 UTC, zubkov7 commented on src/components/menuItem/MenuItem.jsx
> +                <input type={"button"} value={"-"} onClick={decrement} disabled={count <= MIN}/>
давайте вынесем каунтер в отдельный компонент

для инкремента и декремента логичнее использовать тег <button />

2024-07-13 14:27 UTC, zubkov7 requested changes

2024-07-13 14:27 UTC, zubkov7 commented on src/components/navTabs/NavTabs.jsx
> +export const NavTabs = ({elements}) => {
по неймингу компонент не отражает то, что он делает

предлагаю вынести отдельно компонент Tab и в него передавать необходимые пропсы: название ресторана, onClick, isActive

сейчас не очень оптимально реализовано с логикой активного ресторана - для каждого отдельного массива генерируем компонент

предлагаю из массива ресторанов сгенерировать табы, клик на таб вызывает setRestId с нужным айди

setRestId устанавливает активный айди ресторана

activeRest можно найти rest.find по айди

2024-07-13 14:27 UTC, zubkov7 commented
прогоните еще пожалуйста prettier, чтобы отформатировать код

2024-07-13 14:30 UTC, zubkov7 commented on src/components/navTabs/NavTabs.jsx
> +                    return <input
для таба тоже логичнее использовать <button />

2024-07-13 14:34 UTC, trichinella commented on src/components/menuItem/MenuItem.jsx
> +                <input type={"button"} value={"-"} onClick={decrement} disabled={count <= MIN}/>
> давайте вынесем каунтер в отдельный компонент

сделаю
для инкремента и декремента логичнее использовать тег - который тег использовать? не input, а допустим button?

2024-07-13 14:34 UTC, trichinella commented on src/components/navTabs/NavTabs.jsx
> +export const NavTabs = ({elements}) => {
> по неймингу компонент не отражает то, что он делает

принял - переименую

2024-07-13 14:37 UTC, trichinella commented
> прогоните еще пожалуйста prettier, чтобы отформатировать код

у меня PHPStorm c React плагином
там стоит автоформатирование
если что-то из него некорректно - можно озвучить - поправлю настройки его

2024-07-13 14:40 UTC, trichinella commented on src/components/navTabs/NavTabs.jsx
> +                    return <input
не совсем понял комментарий - что именно?

2024-07-13 14:55 UTC, trichinella commented on src/components/menuItem/MenuItem.jsx
> +                <input type={"button"} value={"-"} onClick={decrement} disabled={count <= MIN}/>
> давайте вынесем каунтер в отдельный компонент

сделал

2024-07-13 14:55 UTC, trichinella commented on src/components/navTabs/NavTabs.jsx
> +export const NavTabs = ({elements}) => {
> по неймингу компонент не отражает то, что он делает

переименовал

2024-07-13 15:07 UTC, trichinella commented on src/components/navTabs/NavTabs.jsx
> +export const NavTabs = ({elements}) => {
остальную часть комментария тоже поправил

2024-07-14 14:07 UTC, zubkov7 commented on src/components/menuItem/MenuItem.jsx
> +                <input type={"button"} value={"-"} onClick={decrement} disabled={count <= MIN}/>
> > для инкремента и декремента логичнее использовать тег
> 
> который тег использовать? не input, а допустим button?

да, для кнопок именно button использовать логичнее

2024-07-14 14:08 UTC, zubkov7 commented on src/components/navTabs/NavTabs.jsx
> +                    return <input
тег button, `<button />` изначально так писал без оборачивания в код и гитхаб решил вообще удалить из комментария ((

2024-07-14 14:09 UTC, zubkov7 commented on src/components/App.jsx
> +    return (<Layout>
обычно в таком коде делается перенос на следующую строку после скобки

2024-07-14 14:09 UTC, zubkov7 commented on src/components/App.jsx
> +import {restaurants} from "../constants/mock.js";
обычно добавляются пробелы { restaurants }

2024-07-14 14:10 UTC, zubkov7 commented on src/components/counter/Counter.jsx
> +    const isCanBeLower = () => {
обычно такие утилиты выносят из компонента, потому что на каждый рендер будет создаваться новая функция

можно сделать файл utils рядом с компонентом и туда складывать похожие функции

тут нужно будет просто передавать значение аргументом

2024-07-14 14:15 UTC, zubkov7 commented
давайте заиспользуем тег button и в целом можно мержить, остальное не критично

2024-07-14 15:21 UTC, trichinella commented on src/components/menuItem/MenuItem.jsx
> +                <input type={"button"} value={"-"} onClick={decrement} disabled={count <= MIN}/>
сделал

2024-07-14 15:29 UTC, trichinella commented on src/components/App.jsx
> +import {restaurants} from "../constants/mock.js";
добавил в автоформатирование на эти место пробелы

2024-07-14 18:22 UTC, trichinella commented
> давайте заиспользуем тег button и в целом можно мержить, остальное не критично

принял, сделал

2024-07-14 18:23 UTC, merged