Lecture 4 hw
trichinella/learn-javascript-react pull request #3
Opened 2024-07-17 18:05 UTC by trichinella

исправления по eslint
форма и скролл-прогресс

2024-07-18 11:46 UTC, zubkov7 commented on src/components/App.jsx
> +            <ScrollProgressBar/>
логичнее расположить прогресс бар в самом верху

2024-07-18 11:47 UTC, zubkov7 commented on src/components/counter/Counter.jsx
> +                if (isCanBeLower()) {
лучше сделать в отдельных переменных колбеки, а в пропсы передавать уже. Так код будет чище

2024-07-18 11:49 UTC, zubkov7 commented on src/components/reviewForm/ReviewForm.jsx
> +const producer = (state, action) => {
обычно функцию именуют reducer

2024-07-18 11:52 UTC, zubkov7 requested changes

2024-07-18 11:52 UTC, zubkov7 commented on src/components/scrollProgressBar/ScrollProgressBar.jsx
> +    }, [percentage, onScroll]);
на каждое изменение процента будет заново добавляться event listener. Это лишняя зависимость

2024-07-18 11:59 UTC, trichinella commented on src/components/App.jsx
> +            <ScrollProgressBar/>
поменял местами

2024-07-18 12:00 UTC, trichinella commented on src/components/reviewForm/ReviewForm.jsx
> +const producer = (state, action) => {
переименовал (чутка задумался и назвал не так как хотел))

2024-07-18 12:03 UTC, trichinella commented on src/components/counter/Counter.jsx
> +                if (isCanBeLower()) {
сделал

2024-07-18 12:09 UTC, trichinella commented on src/components/scrollProgressBar/ScrollProgressBar.jsx
> +    }, [percentage, onScroll]);
убрал лишнюю зависимость

2024-07-19 07:26 UTC, zubkov7 commented on src/components/scrollProgressBar/ScrollProgressBar.jsx
> +    const getCurrentPercentage = useCallback(() => {
по сути эта функция - хелпер, можно вынести ее из компонента в отдельный файлик. Сейчас она обернута в useCallback, поэтому новая ссылка создаваться не будет, но это дополнительная логика для реакта все же, можно просто вынести из рендера компонента ее

2024-07-19 07:26 UTC, zubkov7 approved these changes

2024-07-19 08:13 UTC, trichinella commented on src/components/scrollProgressBar/ScrollProgressBar.jsx
> +    const getCurrentPercentage = useCallback(() => {
поправил

2024-07-19 08:13 UTC, merged