lecture 5 hw
trichinella/learn-javascript-react pull request #4
Opened 2024-07-21 11:58 UTC by trichinella

стилизация

2024-07-21 19:02 UTC, zubkov7 requested changes

2024-07-21 19:02 UTC, zubkov7 commented on src/components/counter/Counter.jsx
> +            <button className={"button button-sm"} type={"button"} onClick={tryDecrement} disabled={!isCanBeLower()}>-
классы необходимо подключать через модули css:

import styles from './styles.module.css';

<button className={styles.button} />

2024-07-22 07:48 UTC, trichinella commented on src/components/counter/Counter.jsx
> +            <button className={"button button-sm"} type={"button"} onClick={tryDecrement} disabled={!isCanBeLower()}>-
добавил еще в одном файле стилизацию через модули

2024-07-23 09:29 UTC, zubkov7 commented on src/components/button/Button.jsx
> +        [styles.button]: true,
обычно, если нужно безусловно подключать, то используют такой синтаксис:

`classNames(styles.button, {...})`

2024-07-23 09:30 UTC, zubkov7 commented on src/components/button/Button.jsx
> +            disabled={typeof disabled !== "undefined" ? disabled : false}>
можно просто к boolean привести

2024-07-23 09:31 UTC, zubkov7 commented on src/components/reviewForm/ReviewForm.jsx
> +        <label className={styles['review-form-label']}>
обычно для именования применяют camelCase и тут просто через точку можно обращаться

2024-07-23 09:31 UTC, zubkov7 commented on src/components/reviewForm/ReviewForm.jsx
> +            className={"form-input"}
необходимо использовать класс через модуль

2024-07-23 09:56 UTC, trichinella commented on src/components/button/Button.jsx
> +        [styles.button]: true,
поправил

2024-07-23 09:57 UTC, trichinella commented on src/components/button/Button.jsx
> +            disabled={typeof disabled !== "undefined" ? disabled : false}>
по мере сил скрытую типизацию предпочитаю избегать

2024-07-23 10:03 UTC, trichinella commented on src/components/reviewForm/ReviewForm.jsx
> +        <label className={styles['review-form-label']}>
поменял

2024-07-23 10:16 UTC, zubkov7 approved these changes

2024-07-23 11:59 UTC, merged