lecture 7 (homework 6)
trichinella/learn-javascript-react pull request #6
Opened 2024-07-27 11:40 UTC by trichinella

redux

2024-07-28 09:44 UTC, zubkov7 commented
пробегитесь пожалуйста по проекту и проверьте везде ли корректно используете стили через модули. С частью редакса все ок

2024-07-28 09:44 UTC, zubkov7 requested changes

2024-07-28 09:44 UTC, zubkov7 commented on src/components/counter/Counter.jsx
> +        <div className={"dish-item-count-block"}>
необходимо добавлять классы через модули стилей компонента

2024-07-28 09:44 UTC, zubkov7 commented on src/components/reviewList/ReviewList.jsx
>              <h3 className={"small-header"}>Reviews</h3>
и тут

2024-07-28 11:17 UTC, trichinella commented
> пробегитесь пожалуйста по проекту и проверьте везде ли корректно используете стили через модули. С частью редакса все ок

поправил

2024-07-28 11:17 UTC, trichinella commented on src/components/reviewList/ReviewList.jsx
>              <h3 className={"small-header"}>Reviews</h3>
поправил

2024-07-28 11:17 UTC, trichinella commented on src/components/counter/Counter.jsx
> +        <div className={"dish-item-count-block"}>
поправил

2024-07-29 08:53 UTC, zubkov7 approved these changes

2024-07-29 09:19 UTC, merged