homework
trichinella/learn-javascript-react pull request #8
Opened 2024-08-03 15:00 UTC by trichinella

2024-08-05 08:21 UTC, zubkov7 commented on src/components/dish/Dish.jsx
> +    if (requestStatus === RequestStatuses.PENDING || (!dish && requestStatus === RequestStatuses.IDLE)) {
при статусе IDLE не должно быть dish, поэтому проверка излишняя, можно оставить PENDING || IDLE

в целом так ок, смотрят на статус реквеста и рисует какие-то скелетоны. Также можно сделать, чтобы хук useRequest, возвращал isLoading, isError и тд

2024-08-05 08:23 UTC, zubkov7 commented on src/components/review/Review.jsx
> +    const requestStatus = useRequest(getUsers);
пользователей лучше грузить рядом со списком отзывов, чтобы когда отзывы загрузились, была возможность сразу отобразить отзывы

2024-08-05 08:24 UTC, zubkov7 commented on src/components/reviewList/ReviewList.jsx
> +            <div className={"review-list"}>
стили необходимо добавлять через css модули

2024-08-05 08:30 UTC, zubkov7 requested changes

2024-08-05 08:30 UTC, zubkov7 commented on src/redux/entities/dish/dishSlice.js
> +        builder.addCase(getDishesByRestaurant.fulfilled, (state, {payload, meta}) => {
тут немного намешана логика. Сущность ресторана хранит в себе список id позиций меню. Оттуда мы можем достать список. В dishSlice необходимо хранить только сущности меню, без связи с рестораном

давайте еще заиспользуем createEntityAdapter

2024-08-05 08:30 UTC, zubkov7 commented on src/redux/entities/restaurant/getRestaurantById.js
> +            return selectRestaurantById(getState(), id).length === 0;
почему тут смотрим на длину? по идее достаем конкретную сущность по id

2024-08-05 08:30 UTC, zubkov7 commented on src/redux/entities/review/reviewSlice.js
> +        builder.addCase(getReviewsByRestaurant.fulfilled, (state, {payload, meta}) => {
тут аналогично, как с позициями меню

2024-08-05 11:28 UTC, trichinella commented on src/redux/entities/dish/dishSlice.js
> +        builder.addCase(getDishesByRestaurant.fulfilled, (state, {payload, meta}) => {
если не будет связи с рестораном - будут все entities в одном объекте
если мы откроем один ресторан - в entities добавятся 3 блюда
а если другой - добавятся еще 2
получится сразу 5 в одном объекте и отличить какой от кого не сможем

как это сделать?

2024-08-05 11:33 UTC, trichinella commented on src/redux/entities/restaurant/getRestaurantById.js
> +            return selectRestaurantById(getState(), id).length === 0;
поправил

2024-08-05 11:34 UTC, trichinella commented on src/components/reviewList/ReviewList.jsx
> +            <div className={"review-list"}>
поправил

2024-08-05 12:17 UTC, zubkov7 commented on src/redux/entities/dish/dishSlice.js
> +        builder.addCase(getDishesByRestaurant.fulfilled, (state, {payload, meta}) => {
в этом ничего страшного, связь между меню и рестораном, хранится в сущности ресторана и так, там уже есть связь для этого

2024-08-05 13:08 UTC, trichinella commented on src/redux/entities/dish/dishSlice.js
> +        builder.addCase(getDishesByRestaurant.fulfilled, (state, {payload, meta}) => {
а, понял, спасибо

2024-08-06 07:25 UTC, trichinella commented on src/redux/entities/dish/dishSlice.js
> +        builder.addCase(getDishesByRestaurant.fulfilled, (state, {payload, meta}) => {
поправил

2024-08-06 07:58 UTC, trichinella commented on src/components/dish/Dish.jsx
> +    if (requestStatus === RequestStatuses.PENDING || (!dish && requestStatus === RequestStatuses.IDLE)) {
поправил
сделал

2024-08-06 07:58 UTC, trichinella commented on src/components/review/Review.jsx
> +    const requestStatus = useRequest(getUsers);
сделал

2024-08-06 08:56 UTC, trichinella commented on src/redux/entities/review/reviewSlice.js
> +        builder.addCase(getReviewsByRestaurant.fulfilled, (state, {payload, meta}) => {
поправил

2024-08-06 14:32 UTC, zubkov7 commented on src/hooks/useRequest.js
> +    return [isLoading, isError, isSuccess];
в данном случае лучше возвращать объектом, чтобы не запутаться в неймингах

почему выбрали именно функции? потребителям просто нужно boolean значение, можно сразу вычисленное отправлять

2024-08-06 14:35 UTC, zubkov7 commented on src/hooks/useRequest.js
> +    useEffect(() => {
сейчас непонятно, что делает функция, так как переменные названы с помощью букв

какую проблему пытаетесь решить?

2024-08-06 14:38 UTC, zubkov7 commented on src/redux/entities/dish/dishSlice.js
> +        hasDishesByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
это должно лежать в сущности ресторана, так как именно он связывает и хранит в 1 месте эту связь, сейчас логика размывается

2024-08-06 14:40 UTC, zubkov7 commented on src/redux/entities/review/reviewSlice.js
> +        hasReviewsByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
тут аналогично

2024-08-06 15:13 UTC, trichinella commented on src/hooks/useRequest.js
> +    useEffect(() => {
переключаемся между меню и отзывами, вызывается опять запрос
он fulfilled сам запрос
но addCase не срабатывает
поэтому остается idle
таким образом мы проверяем стейт промиса - если фулфиллед, а мы видим idle, то в таком случае применяем

2024-08-06 15:33 UTC, trichinella commented on src/redux/entities/dish/dishSlice.js
> +        hasDishesByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
getDishesByRestaurant - грузит блюда
значит он должен работать с dishSlice

этот код получается должен быть тоже в dishSlice - так как устанавливаем в entities блюда
```
builder.addCase(getDishesByRestaurant.fulfilled, (state, {payload, meta}) => {
            entityAdapter.setMany(state, payload);
            state.restaurants[meta.arg] = true;
        })
```

и если нужно вынести hasDishesByRestaurantId
то в restaurantSlice нужно добавить 
```
builder.addCase(getDishesByRestaurant.fulfilled, (state, {payload, meta}) => {
            state.restaurants[meta.arg] = true;
        })
```
то есть в двух слайсах смотреть за getDishesByRestaurant

2024-08-06 15:33 UTC, trichinella commented on src/redux/entities/review/reviewSlice.js
> +        hasReviewsByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
аналогично выше комментарий

2024-08-06 15:34 UTC, trichinella commented on src/redux/entities/dish/dishSlice.js
> +        hasDishesByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
или как я вынесу это по-другому?

2024-08-06 15:43 UTC, trichinella commented on src/hooks/useRequest.js
> +    return [isLoading, isError, isSuccess];
поправил

2024-08-06 16:03 UTC, zubkov7 commented on src/redux/entities/dish/dishSlice.js
> +        hasDishesByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
в dishSlice можно хранить только сущности: entities и ids
в restaurantSlice завязываемся на запрос и храним dishIds связь с блюдами

так сущности и связь с ними хранятся в одном экземпляре

2024-08-07 08:22 UTC, trichinella commented on src/redux/entities/dish/dishSlice.js
> +        hasDishesByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
исправил

2024-08-07 08:22 UTC, trichinella commented on src/redux/entities/review/reviewSlice.js
> +        hasReviewsByRestaurantId: (state, restaurantId) => !!state.restaurants[restaurantId],
исправил

2024-08-08 13:09 UTC, zubkov7 commented on src/components/reviewList/ReviewList.jsx
> +    if (reviewRequestError && userRequestError) {
по логике тут должно быть условие ИЛИ

2024-08-08 13:10 UTC, zubkov7 commented on src/hooks/useRequest.js
> +    useEffect(() => {
в любом случае нужно переписать с использованием нейминга, который отражает логику. Сейчас код не читаем

2024-08-08 13:11 UTC, zubkov7 approved these changes

2024-08-08 15:08 UTC, trichinella commented on src/components/reviewList/ReviewList.jsx
> +    if (reviewRequestError && userRequestError) {
поправил

2024-08-08 15:11 UTC, trichinella commented on src/hooks/useRequest.js
> +    useEffect(() => {
поправил

2024-08-08 15:12 UTC, merged